parameters:
  featurefactory:
    feature_sources:
      - path: "./features_person"
        prefix: "local"
      - path: "../odap-fs-demo-global/features_person"
        prefix: "global"

    preview_catalog: "on"
    catalog: "{write_env}"
    database: "fs_demo_features_{entity}"

    features:
      latest_table: "features_latest"

    metadata:
      table: "metadata"

    checkpoint_dir: "dbfs:/odap-fs/checkpoints"
    checkpoint_interval: 5

    entities:
      person:
        id_column: "person_id"
        id_column_type: "long"
