parameters:
  featurefactory:
    feature_sources:
      - path: "./features_person"
        prefix: "local"

    preview_catalog: "on"
    catalog: "{write_env}"
    database: "nn_demo_features_{entity}"

    features:
      latest_table: "features_latest"

    metadata:
      table: "metadata"

    checkpoint_dir: "dbfs:/odap-fs/checkpoints"
    checkpoint_interval: 5

    entities:
      person:
        id_column: "person_id"
        id_column_type: "long"
